# ------------------------------------------------------
#
# Build and tag local images.
#
# ------------------------------------------------------
#
# Requires:
#  - pg_version - full version of Postgres version
#
# Provides:
#  - local docker image(s).
#
#--
- name: Set facts (pg_major)
  ansible.builtin.set_fact:
    pg_major: "{{ pg_version | regex_replace('^([0-9]+).*$', '\\1') }}"

- name: 'Build docker image {{ pg_version }} (for pgxnclient development)'
  community.docker.docker_image:
    name: '{{ pgxnclient_name }}'
    build:
      path: ../../docker
      target: 'pgxnclient'
      args:
        POSTGRES_MAJOR: '{{ pg_major }}'
        POSTGRES_VERSION: '{{ pg_version }}'
    tag: '{{ pg_version }}'
    source: build

- name: 'Build docker image {{ pg_version }} (for pl/java)'
  community.docker.docker_image:
    name: '{{ pljava_name }}'
    build:
      path: ../../docker
      args:
        POSTGRES_MAJOR: '{{ pg_major }}'
        POSTGRES_VERSION: '{{ pg_version }}'
    tag: '{{ pg_version }}'
    source: build

# ------------------------------------------------------
# Tag local images
# ------------------------------------------------------
- name: 'Tag docker images {{ pg_major }}'
  community.docker.docker_image:
    name: '{{ name }}:{{ pg_version }}'
    repository: '{{ name }}:{{ pg_major }}'
    force_tag: true
    source: local
  loop:
    - '{{ pgxnclient_name }}'
    - '{{ pljava_name }}'
  loop_control:
    loop_var: name


# ------------------------------------------------------
# Tag latest image
# ------------------------------------------------------
- name: 'Tag latest docker images'
  community.docker.docker_image:
    name: '{{ name }}:{{ pg_version }}'
    repository: '{{ name }}:latest'
    force_tag: true
    source: local
  loop:
    - '{{ pgxnclient_name }}'
    - '{{ pljava_name }}'
  loop_control:
    loop_var: name
  when: pg_major == postgres_latest_major_tag
