---
# tasks file for pljava_docker


# bit of a cheat for now...
- name: Create set of tags to build
  ansible.builtin.set_fact:
    tags:
      - '15.2'

- name: Get list of postgresql tags
  vars:
    repo: '{{ postgres_name }}'
  ansible.builtin.include_tasks: list-tags.yml

- name: Set facts (postgres_tags)
  ansible.builtin.set_fact:
    postgres_tags: '{{ full_tags }}'
    postgres_latest_major_tag: '{{ latest_major_tag }}'

- name: Build docker images
  ansible.builtin.include_tasks: build-images.yml
  loop: '{{ tags }}'
  loop_control:
    loop_var: pg_version
  when:
    - tags is defined
    - tags[0] is defined

- name: Log into docker hub
  community.docker.docker_login:
    username: "{{ lookup('ansible.builtin.env', 'DOCKERHUB_USERNAME') }}"
    password: "{{ lookup('ansible.builtin.env', 'DOCKERHUB_PASSWORD') }}"
  register: login_resp
  when:
    - tags is defined
    - tags[0] is defined

- name: Verify we succeeded
  ansible.builtin.assert:
    that:
      - not login_resp.failed
    msg: Unable to log into Docker Hub

- name: Push docker images to docker hub
  ansible.builtin.include_tasks: push-images.yml
  loop: '{{ tags }}'
  loop_control:
    loop_var: pg_version
  when:
    - tags is defined
    - tags[0] is defined

- name: Log out of docker hub
  community.docker.docker_login:
    state: absent
