# ------------------------------------------------------
#
# Push local images to dockerhub
#
# ------------------------------------------------------
#
# Requires:
#  - version - version to push
#
# ------------------------------------------------------
#
# Push local images to docker hub
#
---

- name: 'Push docker images for ({{ version }})'
  community.docker.docker_image:
    name: '{{ item }}:{{ version }}'
    repository: '{{ item }}:{{ version }}'
    force_version: true
    push: true
    source: local
  loop:
    - '{{ pgxnclient_name }}'
    - '{{ pljava_name }}'
    - '{{ pljava_dev_name }}'