---

# Docker names (to ensure consistency)
postgres_name: library/postgres
pgxnclient_name: beargiles/postgres-pgxnclient
pljava_name: beargiles/postgres-pljava
pljava_dev_name: beargiles/postgres-pljava-dev

# we can ignore tese tags since the release is so old.
seed_tags:
  - '12'
  - '12.0'
  - '12.1'
  - '12.2'
  - '12.3'
  - '12.4'
  - '12.5'
  - '12.6'
  - '12.7'
  - '12.8'
  - '12.9'
  - '12.10'
  - '12.11'
  - '12.12'
  - '12.13'
  # '12.14'
  # '12.15'
  - '13'
  - '13.0'
  - '13.1'
  - '13.2'
  - '13.3'
  - '13.4'
  - '13.5'
  - '13.6'
  - '13.7'
  - '13.8'
  - '13.9'
  # '13.10'
  # '13.11'
  - '14'
  - '14.0'
  - '14.1'
  - '14.2'
  - '14.3'
  - '14.4'
  - '14.5'
  - '14.6'
  # '14.7'
  # '14.8'
  - '15'
  - '15.0'
  - '15.1'
  # '15.2'
  # '15.3'
