# ------------------------------------------------------
#
# Push local images to dockerhub
#
# ------------------------------------------------------
#
# Requires:
#  - tags - versions to push
#
# ------------------------------------------------------
#
# Push local images to docker hub
#
---

- name: 'Push docker image for pgxn-client'
  community.docker.docker_image:
    name: '{{ pgxnclient_name}}:{{ item }}'
    repository: '{{ pgxnclient_name }}:{{ item }}'
    force_tag: true
    push: true
    source: local
  loop: '{{ tags }}'

- name: 'Push docker image for pl/java'
  community.docker.docker_image:
    name: '{{ pljava_name}}:{{ item }}'
    repository: '{{ pljava_name }}:{{ item }}'
    force_tag: true
    push: true
    source: local
  loop: '{{ tags }}'

- name: 'Push docker image for pl/java development'
  community.docker.docker_image:
    name: '{{ pljava_name}}:{{ item }}'
    repository: '{{ pljava_dev_name }}:{{ item }}'
    force_tag: true
    push: true
    source: local
  loop: '{{ tags }}'