# ------------------------------------------------------
#
# Push local images to dockerhub
#
# ------------------------------------------------------
#
# Requires:
#  - tag - tag to push
#
# ------------------------------------------------------
#
# Push local images to docker hub
#
---

- name: 'Push docker image for pgxn-client ({{ tag }})'
  community.docker.docker_image:
    name: '{{ pgxnclient_name}}:{{ tag }}'
    repository: '{{ pgxnclient_name }}:{{ tag }}'
    force_tag: true
    push: true
    source: local

- name: 'Push docker image for pl/java'
  community.docker.docker_image:
    name: '{{ pljava_name}}:{{ tag }}'
    repository: '{{ pljava_name }}:{{ tag }}'
    force_tag: true
    push: true
    source: local

- name: 'Push docker image for pl/java development'
  community.docker.docker_image:
    name: '{{ pljava_name}}:{{ tag }}'
    repository: '{{ pljava_dev_name }}:{{ tag }}'
    force_tag: true
    push: true
    source: local