name: Docker PostgreSQL pl/java CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix: 
        postgres: [15]
        variant: [default]


    name: Build docker image for ${{ matrix.postgres }} variant ${{ matrix.variant }}

    runs-on: ubuntu-22.04
    env:
      VERSION: ${{ matrix.postgres }}
      VARIANT: ${{ matrix.variant }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build docker image for ${{ env.VERSION }} ${{ env.VARIANT }}
        run: make test


      - name: Login to dockerhub
        uses: docker/login-action@v1
        # if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
        if: ${{ (github.event_name != 'pull_request')  }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push docker image to dockerhub
        # if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
        if: ${{  (github.event_name != 'pull_request')  }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: make push

